/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
If you want to view the source, please visit the GitHub repository:
https://github.com/sunnys-santhosh/deep-vault
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => DeepVaultPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian4 = require("obsidian");

// src/utils/helpers.ts
function formatTime(date) {
  return date.toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" });
}
function formatDate(date) {
  return date.toLocaleDateString([], { month: "short", day: "numeric", year: "numeric" });
}

// src/api/claude.ts
var import_obsidian = require("obsidian");
var SYSTEM_PROMPT = "You are Deep Vault, an expert research assistant embedded in Obsidian. Help researchers analyze notes, extract insights, identify knowledge gaps, find connections, and synthesize ideas. Be concise, structured, and use markdown formatting. Use bullet points and headers to organize responses clearly.";
async function callClaude(settings, messages, useWeb) {
  var _a, _b;
  const body = {
    model: settings.model,
    max_tokens: settings.maxTokens,
    system: SYSTEM_PROMPT,
    messages
  };
  if (useWeb && settings.enableWebSearch) {
    body.tools = [{ type: "web_search_20250305", name: "web_search" }];
  }
  const response = await (0, import_obsidian.requestUrl)({
    url: "https://api.anthropic.com/v1/messages",
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      "x-api-key": settings.apiKey,
      "anthropic-version": "2023-06-01",
      "anthropic-beta": "web-search-2025-03-05"
    },
    body: JSON.stringify(body),
    throw: false
  });
  if (response.status !== 200) {
    const err = response.json;
    throw new Error((_b = (_a = err == null ? void 0 : err.error) == null ? void 0 : _a.message) != null ? _b : `API error ${response.status}`);
  }
  const data = response.json;
  return data.content.filter((b) => b.type === "text").map((b) => b.text).join("\n") || "No response received.";
}

// src/types.ts
var DEEP_VAULT_VIEW = "deep-vault-view";
var DEFAULT_MODEL = "claude-sonnet-4-20250514";
var DEFAULT_TEMPLATES = [
  {
    id: "tpl-1",
    name: "Executive Summary",
    icon: "\u{1F4CB}",
    prompt: "Write a crisp executive summary of this note in 3 sentences, suitable for sharing with a non-expert audience:",
    useNoteContext: true,
    createdAt: new Date().toISOString()
  },
  {
    id: "tpl-2",
    name: "Critical Analysis",
    icon: "\u{1F52C}",
    prompt: "Critically analyse this note. What are the strongest arguments? What assumptions are made? What are the weakest points?",
    useNoteContext: true,
    createdAt: new Date().toISOString()
  },
  {
    id: "tpl-3",
    name: "Explain Simply",
    icon: "\u{1F9D2}",
    prompt: "Explain the main ideas of this note as if explaining to a curious 12-year-old with no background knowledge:",
    useNoteContext: true,
    createdAt: new Date().toISOString()
  },
  {
    id: "tpl-4",
    name: "Action Items",
    icon: "\u2705",
    prompt: "Based on this note, generate a prioritised list of concrete action items and next steps I should take:",
    useNoteContext: true,
    createdAt: new Date().toISOString()
  },
  {
    id: "tpl-5",
    name: "Counter Arguments",
    icon: "\u2694\uFE0F",
    prompt: "Generate the strongest possible counter-arguments and opposing viewpoints to the ideas presented in this note:",
    useNoteContext: true,
    createdAt: new Date().toISOString()
  },
  {
    id: "tpl-6",
    name: "Tweet Thread",
    icon: "\u{1F426}",
    prompt: "Turn the key ideas from this note into an engaging Twitter/X thread of 5 tweets. Make it accessible and interesting:",
    useNoteContext: true,
    createdAt: new Date().toISOString()
  }
];
var DEFAULT_SETTINGS = {
  apiKey: "",
  model: DEFAULT_MODEL,
  maxTokens: 2e3,
  enableWebSearch: true,
  exportFolder: "Deep Vault Exports",
  templates: DEFAULT_TEMPLATES,
  hasSeenWizard: false
};

// src/modals.ts
var import_obsidian2 = require("obsidian");
var NoteSuggestModal = class extends import_obsidian2.SuggestModal {
  constructor(app, files, onSelect) {
    super(app);
    this.selected = [];
    this.files = files;
    this.onSelect = onSelect;
    this.setPlaceholder("Search and select notes to synthesize (Enter to add, Esc when done)...");
  }
  getSuggestions(query) {
    return this.files.filter(
      (f) => f.basename.toLowerCase().includes(query.toLowerCase())
    ).slice(0, 20);
  }
  renderSuggestion(file, el) {
    const isSelected = this.selected.includes(file);
    el.createEl("div", {
      text: `${isSelected ? "\u2705 " : ""}${file.basename}`,
      cls: isSelected ? "dv-modal-selected" : ""
    });
    el.createEl("small", { text: file.path, cls: "dv-modal-path" });
  }
  onChooseSuggestion(file, _evt) {
    if (!this.selected.includes(file)) {
      this.selected.push(file);
      new import_obsidian2.Notice(`Added: ${file.basename} (${this.selected.length} selected)`);
    } else {
      this.selected = this.selected.filter((f) => f !== file);
      new import_obsidian2.Notice(`Removed: ${file.basename}`);
    }
    this.onSelect(this.selected);
  }
  selectSuggestion(value, evt) {
    this.onChooseSuggestion(value, evt);
    this.inputEl.dispatchEvent(new Event("input"));
  }
};
var TemplateEditorModal = class extends import_obsidian2.Modal {
  constructor(app, existing, onSave) {
    super(app);
    this.existing = existing;
    this.onSave = onSave;
  }
  onOpen() {
    var _a, _b, _c, _d, _e, _f, _g, _h;
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("dv-modal");
    contentEl.createEl("h2", { text: this.existing ? "\u270F\uFE0F Edit Template" : "\u{1F4DD} New Template", cls: "dv-modal-title" });
    contentEl.createEl("label", { text: "Template Name", cls: "dv-modal-label" });
    const nameInput = contentEl.createEl("input", {
      cls: "dv-modal-input",
      attr: { type: "text", placeholder: "e.g. Meeting Summary", value: (_b = (_a = this.existing) == null ? void 0 : _a.name) != null ? _b : "" }
    });
    contentEl.createEl("label", { text: "Icon (emoji)", cls: "dv-modal-label" });
    const iconInput = contentEl.createEl("input", {
      cls: "dv-modal-input dv-modal-input-sm",
      attr: { type: "text", placeholder: "\u{1F4DD}", value: (_d = (_c = this.existing) == null ? void 0 : _c.icon) != null ? _d : "\u{1F4DD}" }
    });
    contentEl.createEl("label", { text: "Prompt", cls: "dv-modal-label" });
    contentEl.createEl("p", { text: "Write your prompt. Claude will receive this, optionally followed by your note content.", cls: "dv-modal-hint" });
    const promptInput = contentEl.createEl("textarea", {
      cls: "dv-modal-textarea",
      attr: { placeholder: "e.g. Summarise this note as a bullet list suitable for a team standup..." }
    });
    promptInput.value = (_f = (_e = this.existing) == null ? void 0 : _e.prompt) != null ? _f : "";
    const toggleRow = contentEl.createDiv("dv-modal-toggle-row");
    toggleRow.createEl("label", { text: "Include current note as context", cls: "dv-modal-toggle-label" });
    const toggleInput = toggleRow.createEl("input", {
      attr: { type: "checkbox" }
    });
    toggleInput.checked = (_h = (_g = this.existing) == null ? void 0 : _g.useNoteContext) != null ? _h : true;
    contentEl.createEl("p", { text: "Quick insert:", cls: "dv-modal-label" });
    const varRow = contentEl.createDiv("dv-modal-var-row");
    const vars = [
      { label: "{{note_title}}", desc: "Note title" },
      { label: "{{date}}", desc: "Today's date" }
    ];
    for (const v of vars) {
      const chip = varRow.createEl("button", { text: v.label, cls: "dv-var-chip", attr: { title: v.desc } });
      chip.onclick = () => {
        var _a2;
        const pos = (_a2 = promptInput.selectionStart) != null ? _a2 : promptInput.value.length;
        promptInput.value = promptInput.value.slice(0, pos) + v.label + promptInput.value.slice(pos);
        promptInput.focus();
      };
    }
    const btnRow = contentEl.createDiv("dv-modal-btn-row");
    const cancelBtn = btnRow.createEl("button", { text: "Cancel", cls: "dv-btn-ghost" });
    cancelBtn.onclick = () => this.close();
    const saveBtn = btnRow.createEl("button", { text: this.existing ? "Save Changes" : "Create Template", cls: "dv-btn-primary" });
    saveBtn.onclick = () => {
      var _a2, _b2, _c2, _d2;
      const name = nameInput.value.trim();
      const prompt = promptInput.value.trim();
      if (!name) {
        new import_obsidian2.Notice("Please enter a template name.");
        return;
      }
      if (!prompt) {
        new import_obsidian2.Notice("Please enter a prompt.");
        return;
      }
      const tpl = {
        id: (_b2 = (_a2 = this.existing) == null ? void 0 : _a2.id) != null ? _b2 : `tpl-${Date.now()}`,
        name,
        icon: iconInput.value.trim() || "\u{1F4DD}",
        prompt,
        useNoteContext: toggleInput.checked,
        createdAt: (_d2 = (_c2 = this.existing) == null ? void 0 : _c2.createdAt) != null ? _d2 : new Date().toISOString()
      };
      this.onSave(tpl);
      this.close();
    };
  }
  onClose() {
    this.contentEl.empty();
  }
};
var SetupWizardModal = class extends import_obsidian2.Modal {
  constructor(app, plugin) {
    super(app);
    this.step = 0;
    this.steps = [
      {
        title: "\u{1F44B} Welcome to Deep Vault",
        icon: "\u{1F50D}",
        content: (el, plugin, next, _close) => {
          el.createEl("p", { text: "Deep Vault is your AI-powered research assistant inside Obsidian, powered by Anthropic's Claude.", cls: "dv-wizard-text" });
          el.createEl("p", { text: "This quick setup takes less than 2 minutes.", cls: "dv-wizard-text" });
          const features = [
            "\u{1F52C} Research tab \u2014 6 smart quick actions on any note",
            "\u{1F4AC} Chat \u2014 multi-turn conversation with your vault",
            "\u{1F517} Synthesis \u2014 combine and compare multiple notes",
            "\u{1F4DD} Templates \u2014 save and reuse custom prompts",
            "\u{1F50D} Search \u2014 natural language search across all notes",
            "\u{1F4F0} Daily Digest \u2014 summarise recent work automatically"
          ];
          const list = el.createEl("ul", { cls: "dv-wizard-list" });
          features.forEach((f) => list.createEl("li", { text: f }));
          el.createEl("button", { text: "Get Started \u2192", cls: "dv-btn-primary dv-wizard-btn" }).onclick = next;
        }
      },
      {
        title: "\u{1F511} Connect to Claude",
        icon: "\u{1F511}",
        content: (el, plugin, next, _close) => {
          el.createEl("p", { text: "Deep Vault needs an Anthropic API key to power Claude.", cls: "dv-wizard-text" });
          const steps = el.createEl("ol", { cls: "dv-wizard-steps" });
          steps.createEl("li", { text: "Go to console.anthropic.com and sign up" });
          steps.createEl("li", { text: "Navigate to API Keys \u2192 Create Key" });
          steps.createEl("li", { text: "Copy the key (starts with sk-ant-...)" });
          steps.createEl("li", { text: "Paste it below" });
          el.createEl("label", { text: "Your API Key", cls: "dv-modal-label" });
          const keyInput = el.createEl("input", {
            cls: "dv-modal-input",
            attr: { type: "password", placeholder: "sk-ant-..." }
          });
          keyInput.value = plugin.settings.apiKey;
          el.createEl("p", { text: "\u{1F512} Your key is stored locally in Obsidian and never sent anywhere except Anthropic.", cls: "dv-wizard-hint" });
          const btn = el.createEl("button", { text: "Save & Continue \u2192", cls: "dv-btn-primary dv-wizard-btn" });
          btn.onclick = async () => {
            const key = keyInput.value.trim();
            if (!key.startsWith("sk-ant-") && key.length > 0) {
              new import_obsidian2.Notice("That doesn't look like a valid Anthropic API key.");
              return;
            }
            plugin.settings.apiKey = key;
            await plugin.saveSettings();
            next();
          };
          const skipBtn = el.createEl("button", { text: "Skip for now", cls: "dv-btn-ghost dv-wizard-skip" });
          skipBtn.onclick = next;
        }
      },
      {
        title: "\u{1F916} Choose Your Model",
        icon: "\u{1F916}",
        content: (el, plugin, next, _close) => {
          el.createEl("p", { text: "Which Claude model would you like to use?", cls: "dv-wizard-text" });
          const models = [
            {
              id: "claude-sonnet-4-20250514",
              name: "Claude Sonnet 4",
              badge: "\u2B50 Recommended",
              desc: "Best balance of intelligence and speed. Ideal for deep research, synthesis and complex analysis.",
              badgeCls: "dv-wizard-badge-recommended"
            },
            {
              id: "claude-haiku-4-5-20251001",
              name: "Claude Haiku 4.5",
              badge: "\u26A1 Fastest",
              desc: "Quicker responses, lower cost. Great for quick summaries and simple tasks.",
              badgeCls: "dv-wizard-badge-fast"
            }
          ];
          const modelGrid = el.createDiv("dv-wizard-model-grid");
          for (const m of models) {
            const card = modelGrid.createDiv("dv-wizard-model-card");
            if (plugin.settings.model === m.id)
              card.addClass("dv-wizard-model-selected");
            const cardTop = card.createDiv("dv-wizard-model-top");
            cardTop.createEl("span", { text: m.name, cls: "dv-wizard-model-name" });
            cardTop.createEl("span", { text: m.badge, cls: `dv-wizard-badge ${m.badgeCls}` });
            card.createEl("p", { text: m.desc, cls: "dv-wizard-model-desc" });
            card.onclick = async () => {
              modelGrid.querySelectorAll(".dv-wizard-model-card").forEach((c) => c.removeClass("dv-wizard-model-selected"));
              card.addClass("dv-wizard-model-selected");
              plugin.settings.model = m.id;
              await plugin.saveSettings();
            };
          }
          el.createEl("button", { text: "Continue \u2192", cls: "dv-btn-primary dv-wizard-btn" }).onclick = next;
        }
      },
      {
        title: "\u2328\uFE0F Keyboard Shortcuts",
        icon: "\u2328\uFE0F",
        content: (el, _plugin, next, _close) => {
          el.createEl("p", { text: "Deep Vault registers these commands in Obsidian. You can assign hotkeys to any of them in Settings \u2192 Hotkeys.", cls: "dv-wizard-text" });
          const shortcuts = [
            { cmd: "Open Deep Vault panel", hint: "Main panel" },
            { cmd: "Deep Vault: Go to Research tab", hint: "Research" },
            { cmd: "Deep Vault: Go to Chat tab", hint: "Chat" },
            { cmd: "Deep Vault: Go to Search tab", hint: "Search" },
            { cmd: "Deep Vault: Summarise current note", hint: "Quick action" },
            { cmd: "Deep Vault: Auto-tag current note", hint: "Quick action" },
            { cmd: "Deep Vault: Generate daily research digest", hint: "Digest" },
            { cmd: "Deep Vault: Search vault", hint: "Vault search" }
          ];
          const table = el.createEl("table", { cls: "dv-wizard-table" });
          const thead = table.createEl("thead");
          const hrow = thead.createEl("tr");
          hrow.createEl("th", { text: "Command" });
          hrow.createEl("th", { text: "What it does" });
          const tbody = table.createEl("tbody");
          shortcuts.forEach((s) => {
            const row = tbody.createEl("tr");
            row.createEl("td", { text: s.cmd, cls: "dv-wizard-cmd" });
            row.createEl("td", { text: s.hint, cls: "dv-wizard-hint-cell" });
          });
          el.createEl("p", { text: "\u{1F4A1} Tip: Go to Settings \u2192 Hotkeys and search Deep Vault to assign your preferred shortcuts.", cls: "dv-wizard-hint" });
          el.createEl("button", { text: "Continue \u2192", cls: "dv-btn-primary dv-wizard-btn" }).onclick = next;
        }
      },
      {
        title: "\u{1F389} You are ready!",
        icon: "\u{1F389}",
        content: (el, _plugin, _next, close) => {
          el.createEl("p", { text: "Deep Vault is all set up. Here is how to get started:", cls: "dv-wizard-text" });
          const tips = [
            { icon: "1\uFE0F\u20E3", text: "Open any note in your vault" },
            { icon: "2\uFE0F\u20E3", text: "Click the \u{1F50D} icon in the left ribbon" },
            { icon: "3\uFE0F\u20E3", text: "Try Summarize in the Research tab" },
            { icon: "4\uFE0F\u20E3", text: "Ask Claude anything in the Chat tab" }
          ];
          const tipList = el.createDiv("dv-wizard-tips");
          tips.forEach((t) => {
            const row = tipList.createDiv("dv-wizard-tip-row");
            row.createEl("span", { text: t.icon, cls: "dv-wizard-tip-icon" });
            row.createEl("span", { text: t.text, cls: "dv-wizard-tip-text" });
          });
          el.createEl("button", { text: "Open Deep Vault \u{1F680}", cls: "dv-btn-primary dv-wizard-btn" }).onclick = close;
        }
      }
    ];
    this.plugin = plugin;
  }
  onOpen() {
    this.renderStep();
  }
  renderStep() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("dv-wizard-modal");
    const step = this.steps[this.step];
    const progress = contentEl.createDiv("dv-wizard-progress");
    this.steps.forEach((_, i) => {
      progress.createDiv(i <= this.step ? "dv-wizard-dot dv-wizard-dot-active" : "dv-wizard-dot");
    });
    contentEl.createEl("div", { text: step.icon, cls: "dv-wizard-icon" });
    contentEl.createEl("h2", { text: step.title, cls: "dv-wizard-title" });
    const contentArea = contentEl.createDiv("dv-wizard-content");
    step.content(
      contentArea,
      this.plugin,
      () => {
        this.step++;
        if (this.step < this.steps.length)
          this.renderStep();
        else
          this.close();
      },
      () => this.close()
    );
  }
  async onClose() {
    this.plugin.settings.hasSeenWizard = true;
    await this.plugin.saveSettings();
    const leaves = this.app.workspace.getLeavesOfType(DEEP_VAULT_VIEW);
    if (leaves.length === 0) {
      const leaf = this.app.workspace.getRightLeaf(false);
      await leaf.setViewState({ type: DEEP_VAULT_VIEW, active: true });
      this.app.workspace.revealLeaf(leaf);
    }
    this.contentEl.empty();
  }
};

// src/settings.ts
var import_obsidian3 = require("obsidian");
var DeepVaultSettingTab = class extends import_obsidian3.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "\u{1F50D} Deep Vault Settings" });
    new import_obsidian3.Setting(containerEl).setName("Anthropic API Key").setDesc("Get your key from console.anthropic.com \u2014 stored locally, never shared.").addText((text) => text.setPlaceholder("sk-ant-...").setValue(this.plugin.settings.apiKey).onChange(async (value) => {
      this.plugin.settings.apiKey = value.trim();
      await this.plugin.saveSettings();
    }));
    new import_obsidian3.Setting(containerEl).setName("Claude Model").setDesc("Sonnet recommended for research. Haiku is faster and cheaper.").addDropdown((drop) => drop.addOption("claude-sonnet-4-20250514", "Claude Sonnet 4 (Recommended)").addOption("claude-haiku-4-5-20251001", "Claude Haiku 4.5 (Faster)").setValue(this.plugin.settings.model).onChange(async (value) => {
      this.plugin.settings.model = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian3.Setting(containerEl).setName("Max Response Length").setDesc("Higher = longer, more detailed responses.").addSlider((slider) => slider.setLimits(500, 4e3, 250).setValue(this.plugin.settings.maxTokens).setDynamicTooltip().onChange(async (value) => {
      this.plugin.settings.maxTokens = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian3.Setting(containerEl).setName("Enable Web Search").setDesc("Allow Claude to search the web when the \u{1F310} Web button is active in Chat.").addToggle((toggle) => toggle.setValue(this.plugin.settings.enableWebSearch).onChange(async (value) => {
      this.plugin.settings.enableWebSearch = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian3.Setting(containerEl).setName("Export Folder").setDesc("Folder in your vault where exported notes will be saved.").addText((text) => text.setPlaceholder("Deep Vault Exports").setValue(this.plugin.settings.exportFolder).onChange(async (value) => {
      this.plugin.settings.exportFolder = value || "Deep Vault Exports";
      await this.plugin.saveSettings();
    }));
    containerEl.createEl("h3", { text: "What's New in v3.0" });
    const ul = containerEl.createEl("ul");
    ul.createEl("li", { text: "\u{1F4DD} Custom Templates \u2014 save and reuse your own prompts" });
    ul.createEl("li", { text: "\u{1F517} Synthesis tab \u2014 combine & compare multiple notes" });
    ul.createEl("li", { text: "\u{1F4BE} Export any response directly as a new Obsidian note" });
    ul.createEl("li", { text: "\u{1F310} Web search \u2014 Claude can search the internet from Chat" });
    ul.createEl("li", { text: "\u{1F4CB} History export \u2014 save your entire session as a note" });
    containerEl.createEl("h3", { text: "Prompt Templates" });
    const tplCount = this.plugin.settings.templates.length;
    containerEl.createEl("p", {
      text: `You have ${tplCount} template${tplCount !== 1 ? "s" : ""}. Manage them from the \u{1F4DD} Templates tab in the Deep Vault panel.`,
      cls: "setting-item-description"
    });
    const resetBtn = containerEl.createEl("button", { text: "Reset to Default Templates", cls: "mod-warning" });
    resetBtn.style.marginTop = "8px";
    resetBtn.onclick = async () => {
      this.plugin.settings.templates = DEFAULT_TEMPLATES;
      await this.plugin.saveSettings();
      new import_obsidian3.Notice("Templates reset to defaults.");
      this.display();
    };
  }
};

// src/main.ts
function renderMarkdown(container, text) {
  container.empty();
  const lines = text.split("\n");
  let inList = false;
  let listEl = null;
  for (const line of lines) {
    if (line.startsWith("### ")) {
      if (inList) {
        inList = false;
        listEl = null;
      }
      container.createEl("h4", { text: line.slice(4), cls: "dv-md-h3" });
    } else if (line.startsWith("## ")) {
      if (inList) {
        inList = false;
        listEl = null;
      }
      container.createEl("h3", { text: line.slice(3), cls: "dv-md-h2" });
    } else if (line.startsWith("# ")) {
      if (inList) {
        inList = false;
        listEl = null;
      }
      container.createEl("h2", { text: line.slice(2), cls: "dv-md-h1" });
    } else if (line.startsWith("- ") || line.startsWith("\u2022 ")) {
      if (!inList) {
        listEl = container.createEl("ul", { cls: "dv-md-list" });
        inList = true;
      }
      listEl.createEl("li", { text: line.slice(2), cls: "dv-md-li" });
    } else if (line.match(/^\d+\. /)) {
      if (!inList) {
        listEl = container.createEl("ol", { cls: "dv-md-list" });
        inList = true;
      }
      listEl.createEl("li", { text: line.replace(/^\d+\. /, ""), cls: "dv-md-li" });
    } else if (line.startsWith("> ")) {
      if (inList) {
        inList = false;
        listEl = null;
      }
      container.createEl("blockquote", { text: line.slice(2), cls: "dv-md-quote" });
    } else if (line.trim() === "") {
      if (inList) {
        inList = false;
        listEl = null;
      }
    } else {
      if (inList) {
        inList = false;
        listEl = null;
      }
      const p = container.createEl("p", { cls: "dv-md-p" });
      const parts = line.split(/\*\*(.*?)\*\*/g);
      parts.forEach((part, i) => {
        if (i % 2 === 1)
          p.createEl("strong", { text: part });
        else if (part)
          p.appendText(part);
      });
    }
  }
}
var DeepVaultView = class extends import_obsidian4.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.chatHistory = [];
    this.activeTab = "research";
    this.lastResponse = "";
    this.plugin = plugin;
  }
  getViewType() {
    return DEEP_VAULT_VIEW;
  }
  getDisplayText() {
    return "Deep Vault";
  }
  getIcon() {
    return "search";
  }
  async onOpen() {
    var _a;
    const root = this.containerEl.children[1];
    root.empty();
    root.addClass("dv-root");
    const isMobile = (_a = this.app.isMobile) != null ? _a : window.innerWidth < 768;
    if (isMobile)
      root.addClass("dv-mobile");
    this.buildHeader(root);
    this.buildTabs(root);
    this.buildPanelResearch(root);
    this.buildPanelChat(root);
    this.buildPanelSynthesis(root);
    this.buildPanelTemplates(root);
    this.buildPanelSearch(root);
    this.buildPanelHistory(root);
    this.statusEl = root.createDiv("dv-status");
    this.switchTab("research");
    this.addTouchSwipe(root);
  }
  addTouchSwipe(root) {
    let touchStartX = 0;
    let touchStartY = 0;
    const tabOrder = ["research", "chat", "synthesis", "templates", "search", "history"];
    root.addEventListener("touchstart", (e) => {
      touchStartX = e.touches[0].clientX;
      touchStartY = e.touches[0].clientY;
    }, { passive: true });
    root.addEventListener("touchend", (e) => {
      const dx = e.changedTouches[0].clientX - touchStartX;
      const dy = e.changedTouches[0].clientY - touchStartY;
      if (Math.abs(dx) < 60 || Math.abs(dy) > Math.abs(dx))
        return;
      const currentIdx = tabOrder.indexOf(this.activeTab);
      if (dx < 0 && currentIdx < tabOrder.length - 1) {
        this.switchTab(tabOrder[currentIdx + 1]);
      } else if (dx > 0 && currentIdx > 0) {
        this.switchTab(tabOrder[currentIdx - 1]);
      }
    }, { passive: true });
  }
  // ─── Header ───────────────────────────────────────────────────────────────
  buildHeader(root) {
    const header = root.createDiv("dv-header");
    const left = header.createDiv("dv-header-left");
    left.createEl("span", { text: "\u{1F50D}", cls: "dv-logo" });
    const titles = left.createDiv("dv-header-titles");
    titles.createEl("h2", { text: "Deep Vault", cls: "dv-title" });
    titles.createEl("p", { text: "AI Research Assistant", cls: "dv-subtitle" });
    const badge = header.createDiv("dv-badge");
    badge.createEl("span", { text: "Claude", cls: "dv-badge-text" });
  }
  // ─── Tabs ─────────────────────────────────────────────────────────────────
  buildTabs(root) {
    const tabBar = root.createDiv("dv-tab-bar");
    const tabs = [
      { ref: "tabResearch", icon: "\u{1F52C}", label: "Research", tab: "research" },
      { ref: "tabChat", icon: "\u{1F4AC}", label: "Chat", tab: "chat" },
      { ref: "tabSynthesis", icon: "\u{1F517}", label: "Synthesis", tab: "synthesis" },
      { ref: "tabTemplates", icon: "\u{1F4DD}", label: "Templates", tab: "templates" },
      { ref: "tabSearch", icon: "\u{1F50D}", label: "Search", tab: "search" },
      { ref: "tabHistory", icon: "\u{1F4CB}", label: "More", tab: "history" }
    ];
    for (const t of tabs) {
      const el = tabBar.createDiv("dv-tab");
      el.createEl("span", { text: t.icon, cls: "dv-tab-icon" });
      el.createEl("span", { text: t.label, cls: "dv-tab-label" });
      el.onclick = () => this.switchTab(t.tab);
      this[t.ref] = el;
    }
  }
  switchTabPublic(tab) {
    this.switchTab(tab);
  }
  switchTab(tab) {
    var _a;
    this.activeTab = tab;
    const tabs = [this.tabResearch, this.tabChat, this.tabSynthesis, this.tabTemplates, this.tabSearch, this.tabHistory];
    const panels = [this.panelResearch, this.panelChat, this.panelSynthesis, this.panelTemplates, this.panelSearch, this.panelHistory];
    tabs.forEach((t) => t.removeClass("dv-tab-active"));
    panels.forEach((p) => p.addClass("dv-hidden"));
    const map = { research: 0, chat: 1, synthesis: 2, templates: 3, search: 4, history: 5 };
    tabs[map[tab]].addClass("dv-tab-active");
    panels[map[tab]].removeClass("dv-hidden");
    if (tab === "chat")
      (_a = this.chatInputEl) == null ? void 0 : _a.focus();
    if (tab === "templates")
      this.renderTemplates();
    if (tab === "history") {
      this.renderHotkeys();
      this.renderHistory();
    }
  }
  // ─── Research Panel ───────────────────────────────────────────────────────
  buildPanelResearch(root) {
    this.panelResearch = root.createDiv("dv-panel");
    const noteInfo = this.panelResearch.createDiv("dv-note-info");
    noteInfo.createEl("span", { text: "\u{1F4C4} Uses your currently open note as context", cls: "dv-note-label" });
    this.panelResearch.createEl("p", { text: "QUICK ACTIONS", cls: "dv-section-label" });
    const grid = this.panelResearch.createDiv("dv-action-grid");
    const actions = [
      { icon: "\u{1F4C4}", label: "Summarize", action: "summarize", desc: "Key points from this note" },
      { icon: "\u2753", label: "Questions", action: "questions", desc: "Research questions to explore" },
      { icon: "\u{1F4A1}", label: "Concepts", action: "concepts", desc: "Extract core ideas & terms" },
      { icon: "\u{1F52D}", label: "Gaps", action: "gaps", desc: "Missing info & research gaps" },
      { icon: "\u{1F517}", label: "Connections", action: "connections", desc: "Links to other ideas" },
      { icon: "\u{1F4DA}", label: "Literature", action: "literature", desc: "Related research areas" },
      { icon: "\u{1F3F7}", label: "Auto-Tag", action: "autotag", desc: "Suggest & apply tags" }
    ];
    for (const a of actions) {
      const card = grid.createDiv("dv-action-card");
      card.createEl("span", { text: a.icon, cls: "dv-action-icon" });
      card.createEl("span", { text: a.label, cls: "dv-action-label" });
      card.createEl("span", { text: a.desc, cls: "dv-action-desc" });
      card.onclick = () => this.runQuickAction(a.action);
    }
    this.panelResearch.createEl("p", { text: "RESPONSE", cls: "dv-section-label dv-section-label-top" });
    const responseWrap = this.panelResearch.createDiv("dv-response-wrap");
    this._responseEl = responseWrap.createDiv("dv-response");
    this._responseEl.createEl("p", { text: "Select a Quick Action above.", cls: "dv-placeholder" });
    const exportRow = this.panelResearch.createDiv("dv-export-row dv-hidden");
    const exportBtn = exportRow.createEl("button", { text: "\u{1F4BE} Save as Note", cls: "dv-btn-export" });
    exportBtn.onclick = () => this.exportToNote(this.lastResponse, "Research Result");
    this._exportRow = exportRow;
    this.panelResearch.createEl("p", { text: "DAILY DIGEST", cls: "dv-section-label dv-section-label-top" });
    const digestDesc = this.panelResearch.createDiv("dv-digest-desc");
    digestDesc.createEl("span", { text: "Summarise notes you have worked on recently.", cls: "dv-note-label" });
    const digestControls = this.panelResearch.createDiv("dv-digest-controls");
    const rangeSelect = digestControls.createEl("select", { cls: "dv-digest-select" });
    [
      { value: "1", label: "Last 24 hours" },
      { value: "7", label: "Last 7 days" },
      { value: "30", label: "Last 30 days" }
    ].forEach((opt) => {
      const o = rangeSelect.createEl("option", { text: opt.label });
      o.value = opt.value;
    });
    const digestBtn = digestControls.createEl("button", { text: "\u{1F4F0} Generate Digest", cls: "dv-btn-digest" });
    digestBtn.onclick = () => {
      const days = parseInt(rangeSelect.value);
      this.runDailyDigest(days);
    };
    const digestResponseWrap = this.panelResearch.createDiv("dv-response-wrap");
    const digestResponseEl = digestResponseWrap.createDiv("dv-response");
    digestResponseEl.createEl("p", { text: "Click Generate Digest to summarise your recent notes.", cls: "dv-placeholder" });
    this._digestResponseEl = digestResponseEl;
    const digestExportRow = this.panelResearch.createDiv("dv-export-row dv-hidden");
    digestExportRow.createEl("button", { text: "\u{1F4BE} Save Digest as Note", cls: "dv-btn-export" }).onclick = () => this.exportDigestAsNote();
    this._digestExportRow = digestExportRow;
  }
  get responseEl() {
    return this._responseEl;
  }
  // ─── Chat Panel ───────────────────────────────────────────────────────────
  buildPanelChat(root) {
    this.panelChat = root.createDiv("dv-panel dv-panel-chat");
    this.chatMessagesEl = this.panelChat.createDiv("dv-chat-messages");
    this.renderWelcomeMessage();
    const inputArea = this.panelChat.createDiv("dv-chat-input-area");
    this.chatInputEl = inputArea.createEl("textarea", {
      cls: "dv-chat-input",
      attr: { placeholder: "Ask anything... (Enter to send, Shift+Enter for new line)" }
    });
    this.chatInputEl.addEventListener("keydown", (e) => {
      if (e.key === "Enter" && !e.shiftKey) {
        e.preventDefault();
        this.sendChatMessage();
      }
    });
    const inputFooter = inputArea.createDiv("dv-chat-input-footer");
    const clearBtn = inputFooter.createEl("button", { text: "\u{1F5D1} Clear", cls: "dv-btn-ghost" });
    clearBtn.onclick = () => this.clearChat();
    const useNoteBtn = inputFooter.createEl("button", { text: "\u{1F4C4} Note", cls: "dv-btn-ghost" });
    useNoteBtn.onclick = () => {
      const note = this.getCurrentNote();
      if (note) {
        this.chatInputEl.value = `Based on my note "${note.title}": `;
        this.chatInputEl.focus();
      } else
        new import_obsidian4.Notice("Open a note first.");
    };
    const webBtn = inputFooter.createEl("button", { text: "\u{1F310} Web", cls: "dv-btn-ghost dv-web-toggle" });
    webBtn.title = "Toggle web search for this query";
    this._webEnabled = false;
    webBtn.onclick = () => {
      this._webEnabled = !this._webEnabled;
      webBtn.toggleClass("dv-web-active", this._webEnabled);
      webBtn.setText(this._webEnabled ? "\u{1F310} Web ON" : "\u{1F310} Web");
    };
    const sendBtn = inputFooter.createEl("button", { text: "Send \u2192", cls: "dv-btn-primary" });
    sendBtn.onclick = () => this.sendChatMessage();
  }
  renderWelcomeMessage() {
    this.chatMessagesEl.empty();
    const welcome = this.chatMessagesEl.createDiv("dv-chat-welcome");
    welcome.createEl("p", { text: "\u{1F44B} Hi! I'm Deep Vault.", cls: "dv-welcome-title" });
    welcome.createEl("p", { text: "Ask me anything about your research. Enable \u{1F310} Web to search the internet for current information.", cls: "dv-welcome-text" });
    const tips = welcome.createDiv("dv-welcome-tips");
    const examples = [
      "What are the key themes in my note?",
      "Fact-check the claims in my current note",
      "What recent research exists on this topic?"
    ];
    for (const ex of examples) {
      const tip = tips.createEl("button", { text: `"${ex}"`, cls: "dv-example-btn" });
      tip.onclick = () => {
        this.chatInputEl.value = ex;
        this.chatInputEl.focus();
      };
    }
  }
  async sendChatMessage() {
    const input = this.chatInputEl.value.trim();
    if (!input)
      return;
    const note = this.getCurrentNote();
    const useWeb = this._webEnabled && this.plugin.settings.enableWebSearch;
    this.chatInputEl.value = "";
    this.addChatBubble("user", input, note == null ? void 0 : note.title);
    const messages = this.chatHistory.filter((m) => m.role === "user" || m.role === "assistant").map((m) => ({ role: m.role, content: m.content }));
    const userContent = note ? `Context from note "${note.title}":

${note.content.slice(0, 3e3)}

---

${input}` : input;
    messages.push({ role: "user", content: userContent });
    this.chatHistory.push({ role: "user", content: input, timestamp: new Date(), noteTitle: note == null ? void 0 : note.title });
    await this.callClaudeChat(messages, useWeb);
  }
  addChatBubble(role, content, noteTitle) {
    const welcome = this.chatMessagesEl.querySelector(".dv-chat-welcome");
    if (welcome)
      welcome.remove();
    const wrap = this.chatMessagesEl.createDiv(`dv-bubble-wrap dv-bubble-${role}`);
    if (role === "user") {
      if (noteTitle)
        wrap.createEl("span", { text: `\u{1F4C4} ${noteTitle}`, cls: "dv-bubble-note" });
      wrap.createEl("div", { text: content, cls: "dv-bubble dv-bubble-user" });
    } else {
      const bubble = wrap.createDiv("dv-bubble dv-bubble-assistant");
      if (content === "...") {
        bubble.createEl("span", { text: "\u23F3 Thinking...", cls: "dv-thinking" });
      } else {
        renderMarkdown(bubble, content);
        const exportBtn = wrap.createEl("button", { text: "\u{1F4BE} Save as Note", cls: "dv-btn-export-inline" });
        exportBtn.onclick = () => this.exportToNote(content, "Chat Response");
      }
    }
    wrap.createEl("span", { text: formatTime(new Date()), cls: "dv-bubble-time" });
    this.chatMessagesEl.scrollTop = this.chatMessagesEl.scrollHeight;
    return wrap;
  }
  clearChat() {
    this.chatHistory = [];
    this.renderWelcomeMessage();
    new import_obsidian4.Notice("Chat cleared.");
  }
  // ─── Synthesis Panel (v2.1) ───────────────────────────────────────────────
  buildPanelSynthesis(root) {
    this.panelSynthesis = root.createDiv("dv-panel");
    this.panelSynthesis.createEl("p", { text: "MULTI-NOTE SYNTHESIS", cls: "dv-section-label" });
    this.panelSynthesis.createEl("p", {
      text: "Select multiple notes from your vault to synthesize, compare, or review together.",
      cls: "dv-synthesis-desc"
    });
    const selectedArea = this.panelSynthesis.createDiv("dv-selected-notes");
    selectedArea.createEl("p", { text: "No notes selected yet.", cls: "dv-placeholder", attr: { id: "dv-selected-label" } });
    this._selectedNotes = [];
    this._selectedArea = selectedArea;
    const browseBtn = this.panelSynthesis.createEl("button", { text: "\u{1F4C2} Browse & Select Notes", cls: "dv-btn-browse" });
    browseBtn.onclick = () => this.openNotePicker();
    this.panelSynthesis.createEl("p", { text: "SYNTHESIS TYPE", cls: "dv-section-label dv-section-label-top" });
    const synthGrid = this.panelSynthesis.createDiv("dv-synth-grid");
    const synthActions = [
      { icon: "\u{1F4DD}", label: "Summarize All", action: "synth-summarize", desc: "Combined summary" },
      { icon: "\u{1F50D}", label: "Compare", action: "synth-compare", desc: "Similarities & differences" },
      { icon: "\u{1F9E9}", label: "Connect", action: "synth-connect", desc: "Find common themes" },
      { icon: "\u{1F4D6}", label: "Lit Review", action: "synth-litreview", desc: "Academic overview" }
    ];
    for (const a of synthActions) {
      const card = synthGrid.createDiv("dv-action-card");
      card.createEl("span", { text: a.icon, cls: "dv-action-icon" });
      card.createEl("span", { text: a.label, cls: "dv-action-label" });
      card.createEl("span", { text: a.desc, cls: "dv-action-desc" });
      card.onclick = () => this.runSynthesis(a.action);
    }
    this.panelSynthesis.createEl("p", { text: "SYNTHESIS RESULT", cls: "dv-section-label dv-section-label-top" });
    const synthResponseWrap = this.panelSynthesis.createDiv("dv-response-wrap");
    const synthResponse = synthResponseWrap.createDiv("dv-response");
    synthResponse.createEl("p", { text: "Select notes and choose a synthesis type.", cls: "dv-placeholder" });
    this._synthResponseEl = synthResponse;
    const synthExportRow = this.panelSynthesis.createDiv("dv-export-row dv-hidden");
    const synthExportBtn = synthExportRow.createEl("button", { text: "\u{1F4BE} Save Synthesis as Note", cls: "dv-btn-export" });
    synthExportBtn.onclick = () => {
      var _a;
      return this.exportToNote((_a = this._lastSynthResponse) != null ? _a : "", "Synthesis");
    };
    this._synthExportRow = synthExportRow;
  }
  openNotePicker() {
    const files = this.app.vault.getMarkdownFiles();
    new NoteSuggestModal(this.app, files, (selected) => {
      this._selectedNotes = selected;
      this.updateSelectedNotesUI();
    }).open();
  }
  updateSelectedNotesUI() {
    const area = this._selectedArea;
    area.empty();
    const notes = this._selectedNotes;
    if (notes.length === 0) {
      area.createEl("p", { text: "No notes selected yet.", cls: "dv-placeholder" });
      return;
    }
    area.createEl("p", { text: `${notes.length} note${notes.length > 1 ? "s" : ""} selected:`, cls: "dv-selected-count" });
    for (const f of notes) {
      const tag = area.createDiv("dv-note-tag");
      tag.createEl("span", { text: f.basename });
      const removeBtn = tag.createEl("span", { text: " \u2715", cls: "dv-note-tag-remove" });
      removeBtn.onclick = () => {
        this._selectedNotes = notes.filter((n) => n !== f);
        this.updateSelectedNotesUI();
      };
    }
  }
  async runSynthesis(action) {
    const notes = this._selectedNotes;
    if (notes.length < 2) {
      new import_obsidian4.Notice("Please select at least 2 notes to synthesize.");
      return;
    }
    const synthResponseEl = this._synthResponseEl;
    synthResponseEl.empty();
    synthResponseEl.createEl("p", { text: "\u23F3 Synthesizing notes...", cls: "dv-thinking" });
    this.setStatus("\u23F3 Synthesizing...");
    const noteContents = [];
    for (const file of notes) {
      const content = await this.app.vault.read(file);
      noteContents.push(`## ${file.basename}

${content.slice(0, 2e3)}`);
    }
    const combinedNotes = noteContents.join("\n\n---\n\n");
    const prompts = {
      "synth-summarize": `Provide a unified summary across all these research notes, highlighting the most important ideas from each:

${combinedNotes}`,
      "synth-compare": `Compare and contrast these research notes. What are the key similarities and differences?

${combinedNotes}`,
      "synth-connect": `Identify the common themes, connections, and patterns across these research notes:

${combinedNotes}`,
      "synth-litreview": `Write a structured literature review based on these notes, as if preparing an academic overview of the topic:

${combinedNotes}`
    };
    if (!this.plugin.settings.apiKey) {
      synthResponseEl.empty();
      synthResponseEl.createEl("p", { text: "\u26A0\uFE0F Add your API key in Settings \u2192 Deep Vault", cls: "dv-error" });
      this.setStatus("");
      return;
    }
    try {
      const result = await callClaude(this.plugin.settings, [{ role: "user", content: prompts[action] }], false);
      synthResponseEl.empty();
      renderMarkdown(synthResponseEl, result);
      this._lastSynthResponse = result;
      this._synthExportRow.removeClass("dv-hidden");
      this.chatHistory.push({ role: "assistant", content: result, timestamp: new Date() });
    } catch (err) {
      synthResponseEl.empty();
      synthResponseEl.createEl("p", { text: `\u274C ${err.message}`, cls: "dv-error" });
    }
    this.setStatus("");
  }
  // ─── Templates Panel (v3.0.1) ─────────────────────────────────────────────
  buildPanelTemplates(root) {
    this.panelTemplates = root.createDiv("dv-panel");
  }
  renderTemplates() {
    this.panelTemplates.empty();
    const headerRow = this.panelTemplates.createDiv("dv-templates-header");
    headerRow.createEl("p", { text: "MY TEMPLATES", cls: "dv-section-label" });
    const newBtn = headerRow.createEl("button", { text: "+ New", cls: "dv-btn-new-template" });
    newBtn.onclick = () => this.openTemplateEditor();
    const templates = this.plugin.settings.templates;
    if (templates.length === 0) {
      const empty = this.panelTemplates.createDiv("dv-empty-state");
      empty.createEl("p", { text: "\u{1F4DD}", cls: "dv-empty-icon" });
      empty.createEl("p", { text: "No templates yet", cls: "dv-empty-title" });
      empty.createEl("p", { text: "Create your first reusable prompt template", cls: "dv-empty-desc" });
      return;
    }
    const list = this.panelTemplates.createDiv("dv-template-list");
    for (const tpl of templates) {
      this.renderTemplateCard(list, tpl);
    }
    this.panelTemplates.createEl("p", {
      text: "\u{1F4A1} Tip: Templates with Note Context use your open note as input.",
      cls: "dv-template-tip"
    });
  }
  renderTemplateCard(container, tpl) {
    const card = container.createDiv("dv-template-card");
    const cardTop = card.createDiv("dv-template-card-top");
    cardTop.createEl("span", { text: tpl.icon, cls: "dv-template-icon" });
    const cardInfo = cardTop.createDiv("dv-template-info");
    cardInfo.createEl("p", { text: tpl.name, cls: "dv-template-name" });
    cardInfo.createEl("p", { text: tpl.prompt.slice(0, 60) + (tpl.prompt.length > 60 ? "..." : ""), cls: "dv-template-preview" });
    const cardBadge = cardTop.createDiv("dv-template-badges");
    if (tpl.useNoteContext) {
      cardBadge.createEl("span", { text: "\u{1F4C4} Note", cls: "dv-template-badge" });
    }
    const cardActions = card.createDiv("dv-template-card-actions");
    const runBtn = cardActions.createEl("button", { text: "\u25B6 Run", cls: "dv-btn-run-template" });
    runBtn.onclick = () => this.runTemplate(tpl);
    const editBtn = cardActions.createEl("button", { text: "\u270F\uFE0F Edit", cls: "dv-btn-ghost-sm" });
    editBtn.onclick = () => this.openTemplateEditor(tpl);
    const deleteBtn = cardActions.createEl("button", { text: "\u{1F5D1}", cls: "dv-btn-ghost-sm dv-btn-delete" });
    deleteBtn.onclick = async () => {
      this.plugin.settings.templates = this.plugin.settings.templates.filter((t) => t.id !== tpl.id);
      await this.plugin.saveSettings();
      this.renderTemplates();
      new import_obsidian4.Notice(`Template "${tpl.name}" deleted.`);
    };
  }
  openTemplateEditor(existing) {
    new TemplateEditorModal(this.app, existing, async (tpl) => {
      if (existing) {
        const idx = this.plugin.settings.templates.findIndex((t) => t.id === existing.id);
        if (idx !== -1)
          this.plugin.settings.templates[idx] = tpl;
      } else {
        this.plugin.settings.templates.push(tpl);
      }
      await this.plugin.saveSettings();
      this.renderTemplates();
      new import_obsidian4.Notice(`Template "${tpl.name}" ${existing ? "updated" : "created"}!`);
    }).open();
  }
  async runTemplate(tpl) {
    var _a, _b;
    const note = this.getCurrentNote();
    if (tpl.useNoteContext && !note) {
      new import_obsidian4.Notice("This template needs an open note. Please open a note first.");
      return;
    }
    this.switchTab("research");
    const prompt = tpl.useNoteContext && note ? `${tpl.prompt}

# ${note.title}

${note.content.slice(0, 3e3)}` : tpl.prompt;
    this.setStatus(`\u23F3 Running "${tpl.name}"...`);
    this.responseEl.empty();
    this.responseEl.createEl("p", { text: `\u23F3 Running template: ${tpl.icon} ${tpl.name}...`, cls: "dv-thinking" });
    (_a = this._exportRow) == null ? void 0 : _a.addClass("dv-hidden");
    if (!this.plugin.settings.apiKey) {
      this.responseEl.empty();
      this.responseEl.createEl("p", { text: "\u26A0\uFE0F Add your API key in Settings \u2192 Deep Vault", cls: "dv-error" });
      this.setStatus("");
      return;
    }
    try {
      const result = await callClaude(this.plugin.settings, [{ role: "user", content: prompt }], false);
      this.responseEl.empty();
      renderMarkdown(this.responseEl, result);
      this.lastResponse = result;
      (_b = this._exportRow) == null ? void 0 : _b.removeClass("dv-hidden");
      this.chatHistory.push({
        role: "user",
        content: `[Template: ${tpl.name}]${note ? ` on note "${note.title}"` : ""}`,
        timestamp: new Date(),
        noteTitle: note == null ? void 0 : note.title
      });
      this.chatHistory.push({ role: "assistant", content: result, timestamp: new Date() });
    } catch (err) {
      this.responseEl.empty();
      this.responseEl.createEl("p", { text: `\u274C ${err.message}`, cls: "dv-error" });
    }
    this.setStatus("");
  }
  // ─── Vault-Wide Search Panel (v3.0.3) ────────────────────────────────────
  buildPanelSearch(root) {
    this.panelSearch = root.createDiv("dv-panel");
    this.panelSearch.createEl("p", { text: "VAULT-WIDE SEARCH", cls: "dv-section-label" });
    this.panelSearch.createEl("p", {
      text: "Ask Claude anything \u2014 it will search across all your notes to find the answer.",
      cls: "dv-search-desc"
    });
    const searchBox = this.panelSearch.createDiv("dv-search-box");
    const searchInput = searchBox.createEl("textarea", {
      cls: "dv-search-input",
      attr: { placeholder: "e.g. What do my notes say about machine learning? Which notes mention climate change? Summarise everything I know about quantum computing..." }
    });
    searchInput.addEventListener("keydown", (e) => {
      if (e.key === "Enter" && !e.shiftKey) {
        e.preventDefault();
        runSearch();
      }
    });
    const optionsRow = this.panelSearch.createDiv("dv-search-options");
    const folderLabel = optionsRow.createEl("label", { text: "Folder filter (optional):", cls: "dv-search-option-label" });
    const folderInput = optionsRow.createEl("input", {
      cls: "dv-search-folder-input",
      attr: { type: "text", placeholder: "e.g. Research/" }
    });
    const maxLabel = optionsRow.createEl("label", { cls: "dv-search-option-label" });
    const maxSlider = optionsRow.createEl("input", {
      cls: "dv-search-slider",
      attr: { type: "range", min: "5", max: "50", value: "20" }
    });
    const updateMaxLabel = () => maxLabel.setText(`Max notes to search: ${maxSlider.value}`);
    updateMaxLabel();
    maxSlider.addEventListener("input", updateMaxLabel);
    const searchBtn = this.panelSearch.createEl("button", { text: "\u{1F50D} Search Vault", cls: "dv-btn-search" });
    const statsEl = this.panelSearch.createDiv("dv-search-stats dv-hidden");
    this._searchStatsEl = statsEl;
    this.panelSearch.createEl("p", { text: "RESULTS", cls: "dv-section-label dv-section-label-top" });
    const resultsWrap = this.panelSearch.createDiv("dv-response-wrap");
    const resultsEl = resultsWrap.createDiv("dv-response");
    resultsEl.createEl("p", { text: "Enter a question above to search across your vault.", cls: "dv-placeholder" });
    this._searchResultsEl = resultsEl;
    const sourcesEl = this.panelSearch.createDiv("dv-search-sources dv-hidden");
    this._sourcesEl = sourcesEl;
    const searchExportRow = this.panelSearch.createDiv("dv-export-row dv-hidden");
    searchExportRow.createEl("button", { text: "\u{1F4BE} Save Results as Note", cls: "dv-btn-export" }).onclick = () => {
      var _a;
      return this.exportToNote((_a = this._lastSearchResult) != null ? _a : "", "Vault Search Results");
    };
    this._searchExportRow = searchExportRow;
    const runSearch = () => {
      const query = searchInput.value.trim();
      if (!query) {
        new import_obsidian4.Notice("Please enter a search query.");
        return;
      }
      const folder = folderInput.value.trim();
      const maxNotes = parseInt(maxSlider.value);
      this.runVaultSearch(query, folder, maxNotes);
    };
    searchBtn.onclick = runSearch;
  }
  async runVaultSearch(query, folderFilter, maxNotes) {
    const resultsEl = this._searchResultsEl;
    const statsEl = this._searchStatsEl;
    const sourcesEl = this._sourcesEl;
    const exportRow = this._searchExportRow;
    if (!this.plugin.settings.apiKey) {
      resultsEl.empty();
      resultsEl.createEl("p", { text: "\u26A0\uFE0F Add your API key in Settings \u2192 Deep Vault", cls: "dv-error" });
      return;
    }
    resultsEl.empty();
    resultsEl.createEl("p", { text: "\u23F3 Scanning vault...", cls: "dv-thinking" });
    statsEl.addClass("dv-hidden");
    sourcesEl.addClass("dv-hidden");
    exportRow.addClass("dv-hidden");
    this.setStatus("\u23F3 Searching vault...");
    let files = this.app.vault.getMarkdownFiles();
    if (folderFilter) {
      files = files.filter((f) => f.path.startsWith(folderFilter));
    }
    if (files.length === 0) {
      resultsEl.empty();
      resultsEl.createEl("p", { text: `\u274C No notes found${folderFilter ? ` in folder "${folderFilter}"` : ""}.`, cls: "dv-error" });
      this.setStatus("");
      return;
    }
    const keywords = query.toLowerCase().split(/\s+/).filter((w) => w.length > 3);
    const scored = files.map((file) => {
      var _a, _b, _c, _d;
      const cache = this.app.metadataCache.getFileCache(file);
      const headings = (_b = (_a = cache == null ? void 0 : cache.headings) == null ? void 0 : _a.map((h) => h.heading.toLowerCase()).join(" ")) != null ? _b : "";
      const tags = (_d = (_c = cache == null ? void 0 : cache.tags) == null ? void 0 : _c.map((t) => t.tag).join(" ")) != null ? _d : "";
      const score = keywords.reduce((acc, kw) => {
        if (file.basename.toLowerCase().includes(kw))
          acc += 3;
        if (headings.includes(kw))
          acc += 2;
        if (tags.includes(kw))
          acc += 2;
        return acc;
      }, 0);
      return { file, score };
    });
    const topFiles = scored.sort((a, b) => b.score - a.score).slice(0, maxNotes).map((s) => s.file);
    resultsEl.empty();
    resultsEl.createEl("p", { text: `\u23F3 Reading ${topFiles.length} notes...`, cls: "dv-thinking" });
    const noteChunks = [];
    const sourceNames = [];
    for (const file of topFiles) {
      try {
        const content = await this.app.vault.read(file);
        const excerpt = content.slice(0, 800).trim();
        if (excerpt.length > 50) {
          noteChunks.push(`## ${file.basename}

${excerpt}`);
          sourceNames.push(file.basename);
        }
      } catch (e) {
      }
    }
    if (noteChunks.length === 0) {
      resultsEl.empty();
      resultsEl.createEl("p", { text: "\u274C Could not read any matching notes.", cls: "dv-error" });
      this.setStatus("");
      return;
    }
    resultsEl.empty();
    resultsEl.createEl("p", { text: `\u23F3 Asking Claude to synthesize ${noteChunks.length} notes...`, cls: "dv-thinking" });
    const prompt = `You are searching across a user's Obsidian vault to answer their query.

Query: "${query}"

Below are excerpts from ${noteChunks.length} relevant notes. Synthesize a clear, well-structured answer based on what these notes contain. Always cite which notes you're drawing from.

If the notes don't contain enough information to answer the query, say so clearly.

---

${noteChunks.join("\n\n---\n\n")}`;
    try {
      const result = await callClaude(this.plugin.settings, [{ role: "user", content: prompt }], false);
      resultsEl.empty();
      renderMarkdown(resultsEl, result);
      this._lastSearchResult = result;
      statsEl.removeClass("dv-hidden");
      statsEl.empty();
      statsEl.createEl("span", { text: `\u{1F4CA} Searched ${noteChunks.length} of ${files.length} notes`, cls: "dv-search-stat" });
      sourcesEl.removeClass("dv-hidden");
      sourcesEl.empty();
      sourcesEl.createEl("p", { text: "SOURCES", cls: "dv-section-label" });
      const sourceGrid = sourcesEl.createDiv("dv-source-grid");
      sourceNames.slice(0, 12).forEach((name) => {
        const chip = sourceGrid.createEl("span", { text: name, cls: "dv-source-chip" });
        chip.onclick = async () => {
          const file = this.app.vault.getMarkdownFiles().find((f) => f.basename === name);
          if (file) {
            const leaf = this.app.workspace.getLeaf(false);
            await leaf.openFile(file);
          }
        };
      });
      if (sourceNames.length > 12) {
        sourceGrid.createEl("span", { text: `+${sourceNames.length - 12} more`, cls: "dv-source-chip dv-source-more" });
      }
      exportRow.removeClass("dv-hidden");
      this.chatHistory.push({ role: "user", content: `[Vault Search] "${query}"`, timestamp: new Date() });
      this.chatHistory.push({ role: "assistant", content: result, timestamp: new Date() });
    } catch (err) {
      resultsEl.empty();
      resultsEl.createEl("p", { text: `\u274C ${err.message}`, cls: "dv-error" });
    }
    this.setStatus("");
  }
  // ─── History Panel ────────────────────────────────────────────────────────
  buildPanelHistory(root) {
    this.panelHistory = root.createDiv("dv-panel");
    this.panelHistoryTop = this.panelHistory.createDiv("dv-panel-history-top");
    this.panelHistoryBottom = this.panelHistory.createDiv("dv-panel-history-bottom");
  }
  getAssignedHotkey(commandId) {
    var _a;
    const hotkeyManager = this.app.hotkeyManager;
    if (!hotkeyManager)
      return null;
    const hotkeys = (_a = hotkeyManager.getHotkeys(commandId)) != null ? _a : hotkeyManager.getDefaultHotkeys(commandId);
    if (!hotkeys || hotkeys.length === 0)
      return null;
    const modifierLabels = {
      Mod: import_obsidian4.Platform.isMacOS ? "Cmd" : "Ctrl",
      Ctrl: "Ctrl",
      Meta: import_obsidian4.Platform.isMacOS ? "Cmd" : "Win",
      Shift: "Shift",
      Alt: import_obsidian4.Platform.isMacOS ? "Option" : "Alt"
    };
    return hotkeys.map(
      (hk) => [...hk.modifiers.map((m) => {
        var _a2;
        return (_a2 = modifierLabels[m]) != null ? _a2 : m;
      }), hk.key.toUpperCase()].join(" + ")
    ).join(", ");
  }
  renderHotkeys() {
    const panel = this.panelHistoryTop;
    panel.empty();
    panel.createEl("p", { text: "KEYBOARD SHORTCUTS", cls: "dv-section-label" });
    panel.createEl("p", { text: "Assign hotkeys in Settings \u2192 Hotkeys \u2192 search Deep Vault", cls: "dv-hotkey-hint" });
    const shortcuts = [
      { cmd: "Open Deep Vault panel", id: "open-deep-vault", cat: "Navigation" },
      { cmd: "Deep Vault: Go to Research tab", id: "deep-vault-tab-research", cat: "Navigation" },
      { cmd: "Deep Vault: Go to Chat tab", id: "deep-vault-tab-chat", cat: "Navigation" },
      { cmd: "Deep Vault: Go to Synthesis tab", id: "deep-vault-tab-synthesis", cat: "Navigation" },
      { cmd: "Deep Vault: Go to Templates tab", id: "deep-vault-tab-templates", cat: "Navigation" },
      { cmd: "Deep Vault: Go to Search tab", id: "deep-vault-tab-search", cat: "Navigation" },
      { cmd: "Deep Vault: Go to History tab", id: "deep-vault-tab-history", cat: "Navigation" },
      { cmd: "Deep Vault: Summarise current note", id: "deep-vault-summarize", cat: "Actions" },
      { cmd: "Deep Vault: Generate research questions", id: "deep-vault-questions", cat: "Actions" },
      { cmd: "Deep Vault: Extract key concepts", id: "deep-vault-concepts", cat: "Actions" },
      { cmd: "Deep Vault: Find research gaps", id: "deep-vault-gaps", cat: "Actions" },
      { cmd: "Deep Vault: Auto-tag current note", id: "deep-vault-autotag", cat: "Actions" },
      { cmd: "Deep Vault: Generate daily research digest", id: "deep-vault-daily-digest", cat: "Digest" },
      { cmd: "Deep Vault: Search vault", id: "deep-vault-search", cat: "Search" },
      { cmd: "Deep Vault: Open setup wizard", id: "deep-vault-setup-wizard", cat: "Setup" }
    ];
    const cats = [...new Set(shortcuts.map((s) => s.cat))];
    for (const cat of cats) {
      panel.createEl("p", { text: cat.toUpperCase(), cls: "dv-section-label dv-section-label-top" });
      const table = panel.createEl("table", { cls: "dv-hotkey-table" });
      shortcuts.filter((s) => s.cat === cat).forEach((s) => {
        const row = table.createEl("tr");
        row.createEl("td", { text: s.cmd, cls: "dv-hotkey-cmd" });
        const keyText = this.getAssignedHotkey(`${this.plugin.manifest.id}:${s.id}`);
        row.createEl("td", { text: keyText != null ? keyText : "Not set", cls: keyText ? "dv-hotkey-key" : "dv-hotkey-key dv-hotkey-key-unset" });
      });
    }
    const wizardBtn = panel.createEl("button", { text: "\u{1F9D9} Re-run Setup Wizard", cls: "dv-btn-ghost dv-hotkey-wizard-btn" });
    wizardBtn.onclick = () => new SetupWizardModal(this.app, this.plugin).open();
    panel.createEl("p", { text: "ABOUT", cls: "dv-section-label dv-section-label-top" });
    const about = panel.createDiv("dv-about");
    about.createEl("p", { text: `Deep Vault v${this.plugin.manifest.version}`, cls: "dv-about-version" });
    about.createEl("p", { text: "\xA9 2026 Sunny Santhosh. Licensed under the MIT License.", cls: "dv-about-copyright" });
    const links = about.createDiv("dv-about-links");
    const githubLink = links.createEl("a", { text: "GitHub", href: this.plugin.manifest.authorUrl, cls: "dv-about-link" });
    githubLink.setAttr("target", "_blank");
    githubLink.setAttr("rel", "noopener");
    const fundingLink = links.createEl("a", { text: "\u2615 Support", href: this.plugin.manifest.fundingUrl, cls: "dv-about-link" });
    fundingLink.setAttr("target", "_blank");
    fundingLink.setAttr("rel", "noopener");
  }
  renderHistory() {
    this.panelHistoryBottom.empty();
    this.panelHistoryBottom.createEl("p", { text: "SESSION HISTORY", cls: "dv-section-label" });
    if (this.chatHistory.length === 0) {
      const empty = this.panelHistoryBottom.createDiv("dv-empty-state");
      empty.createEl("p", { text: "\u{1F4ED}", cls: "dv-empty-icon" });
      empty.createEl("p", { text: "No history yet", cls: "dv-empty-title" });
      empty.createEl("p", { text: "Start a conversation in Chat or run a Quick Action", cls: "dv-empty-desc" });
      return;
    }
    const exportAllBtn = this.panelHistoryBottom.createEl("button", { text: "\u{1F4BE} Export Full History as Note", cls: "dv-btn-export" });
    exportAllBtn.onclick = () => this.exportHistoryToNote();
    const list = this.panelHistoryBottom.createDiv("dv-history-list");
    for (const msg of [...this.chatHistory].reverse()) {
      const item = list.createDiv(`dv-history-item dv-history-${msg.role}`);
      const itemHeader = item.createDiv("dv-history-item-header");
      itemHeader.createEl("span", { text: msg.role === "user" ? "You" : "Claude", cls: "dv-history-role" });
      itemHeader.createEl("span", { text: formatTime(msg.timestamp), cls: "dv-history-time" });
      if (msg.noteTitle)
        item.createEl("span", { text: `\u{1F4C4} ${msg.noteTitle}`, cls: "dv-history-note" });
      item.createEl("p", { text: msg.content.slice(0, 140) + (msg.content.length > 140 ? "..." : ""), cls: "dv-history-preview" });
      const saveBtn = item.createEl("button", { text: "\u{1F4BE} Save", cls: "dv-btn-save-small" });
      saveBtn.onclick = () => this.exportToNote(msg.content, msg.role === "user" ? "My Question" : "Claude Response");
    }
    const clearBtn = this.panelHistoryBottom.createEl("button", { text: "\u{1F5D1} Clear All History", cls: "dv-btn-danger" });
    clearBtn.onclick = () => {
      this.chatHistory = [];
      this.renderHistory();
      new import_obsidian4.Notice("History cleared.");
    };
  }
  // ─── Export to Note (v2.2) ────────────────────────────────────────────────
  async exportToNote(content, label) {
    if (!content.trim()) {
      new import_obsidian4.Notice("Nothing to export.");
      return;
    }
    const folder = this.plugin.settings.exportFolder;
    const date = formatDate(new Date());
    const time = formatTime(new Date()).replace(":", "-");
    const filename = `${folder}/${label} - ${date} ${time}.md`;
    const noteContent = `---
created: ${new Date().toISOString()}
source: Deep Vault
type: ${label}
---

# ${label}
*Exported from Deep Vault on ${date}*

---

${content}
`;
    try {
      if (!this.app.vault.getAbstractFileByPath(folder)) {
        await this.app.vault.createFolder(folder);
      }
      await this.app.vault.create(filename, noteContent);
      new import_obsidian4.Notice(`\u2705 Saved to "${filename}"`);
      const file = this.app.vault.getAbstractFileByPath(filename);
      if (file) {
        const leaf = this.app.workspace.getLeaf(true);
        await leaf.openFile(file);
      }
    } catch (err) {
      new import_obsidian4.Notice(`\u274C Export failed: ${err.message}`);
    }
  }
  async exportHistoryToNote() {
    if (this.chatHistory.length === 0) {
      new import_obsidian4.Notice("No history to export.");
      return;
    }
    const lines = [
      `---`,
      `created: ${new Date().toISOString()}`,
      `source: Deep Vault`,
      `type: Session History`,
      `---`,
      ``,
      `# Deep Vault Session \u2014 ${formatDate(new Date())}`,
      ``
    ];
    for (const msg of this.chatHistory) {
      lines.push(`## ${msg.role === "user" ? "\u{1F9D1} You" : "\u{1F916} Claude"} \u2014 ${formatTime(msg.timestamp)}`);
      if (msg.noteTitle)
        lines.push(`*Context: ${msg.noteTitle}*`);
      lines.push("");
      lines.push(msg.content);
      lines.push("");
      lines.push("---");
      lines.push("");
    }
    await this.exportToNote(lines.join("\n"), "Session History");
  }
  // ─── API Calls ────────────────────────────────────────────────────────────
  getCurrentNote() {
    const active = this.app.workspace.getActiveViewOfType(import_obsidian4.MarkdownView);
    if (active == null ? void 0 : active.file)
      return { content: active.editor.getValue(), title: active.file.basename };
    const leaves = this.app.workspace.getLeavesOfType("markdown");
    for (const leaf of leaves) {
      const view = leaf.view;
      if (view.file)
        return { content: view.editor.getValue(), title: view.file.basename };
    }
    return null;
  }
  getCurrentFile() {
    const active = this.app.workspace.getActiveViewOfType(import_obsidian4.MarkdownView);
    if (active == null ? void 0 : active.file)
      return active.file;
    const leaves = this.app.workspace.getLeavesOfType("markdown");
    for (const leaf of leaves) {
      const view = leaf.view;
      if (view.file)
        return view.file;
    }
    return null;
  }
  setStatus(msg) {
    this.statusEl.empty();
    if (msg)
      this.statusEl.createEl("span", { text: msg, cls: "dv-status-text" });
  }
  async runQuickAction(action) {
    var _a, _b;
    const note = this.getCurrentNote();
    if (!note) {
      new import_obsidian4.Notice("Please open a note first.");
      return;
    }
    if (action === "autotag") {
      await this.runAutoTag(note);
      return;
    }
    const prompts = {
      summarize: `Summarize this research note in 5 clear bullet points:

# ${note.title}

${note.content}`,
      questions: `Generate 6 insightful research questions to explore next:

# ${note.title}

${note.content}`,
      concepts: `Extract and briefly explain the 6 most important concepts or terms:

# ${note.title}

${note.content}`,
      gaps: `Identify research gaps, missing evidence, and areas needing investigation:

# ${note.title}

${note.content}`,
      connections: `Suggest 5 ways this note connects to other research areas. Be specific:

# ${note.title}

${note.content}`,
      literature: `Suggest 5 related academic topics, authors, or research areas:

# ${note.title}

${note.content}`
    };
    const labels = {
      summarize: "\u23F3 Summarizing...",
      questions: "\u23F3 Generating questions...",
      concepts: "\u23F3 Extracting concepts...",
      gaps: "\u23F3 Finding gaps...",
      connections: "\u23F3 Finding connections...",
      literature: "\u23F3 Researching literature..."
    };
    this.setStatus(labels[action]);
    this.responseEl.empty();
    this.responseEl.createEl("p", { text: labels[action], cls: "dv-thinking" });
    (_a = this._exportRow) == null ? void 0 : _a.addClass("dv-hidden");
    if (!this.plugin.settings.apiKey) {
      this.responseEl.empty();
      this.responseEl.createEl("p", { text: "\u26A0\uFE0F Add your API key in Settings \u2192 Deep Vault", cls: "dv-error" });
      this.setStatus("");
      return;
    }
    try {
      const result = await callClaude(this.plugin.settings, [{ role: "user", content: prompts[action] }], false);
      this.responseEl.empty();
      renderMarkdown(this.responseEl, result);
      this.lastResponse = result;
      (_b = this._exportRow) == null ? void 0 : _b.removeClass("dv-hidden");
      this.chatHistory.push({ role: "user", content: `[Quick Action: ${action}] on note "${note.title}"`, timestamp: new Date(), noteTitle: note.title });
      this.chatHistory.push({ role: "assistant", content: result, timestamp: new Date() });
    } catch (err) {
      this.responseEl.empty();
      this.responseEl.createEl("p", { text: `\u274C ${err.message}`, cls: "dv-error" });
    }
    this.setStatus("");
  }
  // ─── Auto-Tag Notes (v3.0.2) ──────────────────────────────────────────────
  async runAutoTag(note) {
    this.setStatus("\u23F3 Analysing note for tags...");
    this.responseEl.empty();
    this.responseEl.createEl("p", { text: "\u23F3 Asking Claude to suggest tags...", cls: "dv-thinking" });
    if (!this.plugin.settings.apiKey) {
      this.responseEl.empty();
      this.responseEl.createEl("p", { text: "\u26A0\uFE0F Add your API key in Settings \u2192 Deep Vault", cls: "dv-error" });
      this.setStatus("");
      return;
    }
    const existingTags = this.getVaultTags();
    const existingTagsStr = existingTags.length > 0 ? `

Existing tags in this vault (prefer these where relevant): ${existingTags.slice(0, 40).join(", ")}` : "";
    const prompt = `Analyse this note and suggest 5-8 relevant tags for it.${existingTagsStr}

Rules:
- Return ONLY a JSON array of tag strings, nothing else
- Tags should be lowercase, use hyphens for spaces (e.g. "machine-learning")
- No # symbol prefix
- Mix specific and broad tags
- Example output: ["research", "machine-learning", "neural-networks", "deep-learning", "ai", "paper-notes"]

Note to analyse:
# ${note.title}

${note.content.slice(0, 2e3)}`;
    try {
      const result = await callClaude(this.plugin.settings, [{ role: "user", content: prompt }], false);
      const jsonMatch = result.match(/\[.*?\]/s);
      if (!jsonMatch)
        throw new Error("Could not parse tags from response.");
      const suggestedTags = JSON.parse(jsonMatch[0]);
      if (!Array.isArray(suggestedTags) || suggestedTags.length === 0) {
        throw new Error("No tags returned.");
      }
      this.setStatus("");
      this.responseEl.empty();
      this.renderTagPicker(suggestedTags, note);
    } catch (err) {
      this.responseEl.empty();
      this.responseEl.createEl("p", { text: `\u274C ${err.message}`, cls: "dv-error" });
      this.setStatus("");
    }
  }
  getVaultTags() {
    const tags = /* @__PURE__ */ new Set();
    this.app.vault.getMarkdownFiles().forEach((file) => {
      var _a;
      const cache = this.app.metadataCache.getFileCache(file);
      if (cache == null ? void 0 : cache.tags)
        cache.tags.forEach((t) => tags.add(t.tag.replace("#", "")));
      if ((_a = cache == null ? void 0 : cache.frontmatter) == null ? void 0 : _a.tags) {
        const ft = cache.frontmatter.tags;
        if (Array.isArray(ft))
          ft.forEach((t) => tags.add(t));
        else if (typeof ft === "string")
          tags.add(ft);
      }
    });
    return Array.from(tags).sort();
  }
  renderTagPicker(suggestedTags, note) {
    this.responseEl.empty();
    this.responseEl.createEl("p", { text: "\u{1F3F7} Suggested Tags", cls: "dv-autotag-title" });
    this.responseEl.createEl("p", { text: "Click tags to select, then apply to your note.", cls: "dv-autotag-hint" });
    const selected = new Set(suggestedTags);
    const tagGrid = this.responseEl.createDiv("dv-tag-grid");
    const renderTags = () => {
      tagGrid.empty();
      for (const tag of suggestedTags) {
        const chip = tagGrid.createEl("button", {
          text: `#${tag}`,
          cls: selected.has(tag) ? "dv-tag-chip dv-tag-chip-selected" : "dv-tag-chip"
        });
        chip.onclick = () => {
          if (selected.has(tag))
            selected.delete(tag);
          else
            selected.add(tag);
          renderTags();
          updateButtons();
        };
      }
    };
    renderTags();
    const btnRow = this.responseEl.createDiv("dv-autotag-btn-row");
    const selectAllBtn = btnRow.createEl("button", { text: "Select All", cls: "dv-btn-ghost-sm" });
    selectAllBtn.onclick = () => {
      suggestedTags.forEach((t) => selected.add(t));
      renderTags();
      updateButtons();
    };
    const clearBtn = btnRow.createEl("button", { text: "Clear All", cls: "dv-btn-ghost-sm" });
    clearBtn.onclick = () => {
      selected.clear();
      renderTags();
      updateButtons();
    };
    const applyBtn = btnRow.createEl("button", { text: "\u2705 Apply to Note", cls: "dv-btn-primary" });
    applyBtn.onclick = () => this.applyTagsToNote(Array.from(selected), note);
    const updateButtons = () => {
      applyBtn.setText(`\u2705 Apply ${selected.size} Tag${selected.size !== 1 ? "s" : ""} to Note`);
      applyBtn.disabled = selected.size === 0;
    };
    updateButtons();
  }
  async applyTagsToNote(tags, note) {
    if (tags.length === 0) {
      new import_obsidian4.Notice("No tags selected.");
      return;
    }
    const file = this.getCurrentFile();
    if (!file) {
      new import_obsidian4.Notice("Could not find the active note.");
      return;
    }
    let content = await this.app.vault.read(file);
    const hasFrontmatter = content.startsWith("---");
    if (hasFrontmatter) {
      const endIdx = content.indexOf("---", 3);
      if (endIdx !== -1) {
        const frontmatter = content.slice(0, endIdx + 3);
        const rest = content.slice(endIdx + 3);
        if (frontmatter.includes("tags:")) {
          const newFrontmatter = frontmatter.replace(
            /tags:(.*)/,
            (match) => {
              const existing = match.replace("tags:", "").trim();
              if (existing.startsWith("[")) {
                const arr = existing.slice(1, -1).split(",").map((t) => t.trim()).filter(Boolean);
                tags.forEach((t) => {
                  if (!arr.includes(t))
                    arr.push(t);
                });
                return `tags: [${arr.join(", ")}]`;
              } else {
                const newTagLines = tags.map((t) => `
  - ${t}`).join("");
                return match + newTagLines;
              }
            }
          );
          content = newFrontmatter + rest;
        } else {
          const tagLines = tags.map((t) => `  - ${t}`).join("\n");
          content = frontmatter.replace("---", `tags:
${tagLines}
---`).slice(0, -3) + rest;
        }
      }
    } else {
      const tagLines = tags.map((t) => `  - ${t}`).join("\n");
      content = `---
tags:
${tagLines}
---

` + content;
    }
    await this.app.vault.modify(file, content);
    new import_obsidian4.Notice(`\u2705 Applied ${tags.length} tag${tags.length !== 1 ? "s" : ""} to "${note.title}"`);
    this.responseEl.empty();
    this.responseEl.createEl("p", { text: "\u2705 Tags Applied!", cls: "dv-autotag-title" });
    const appliedGrid = this.responseEl.createDiv("dv-tag-grid");
    tags.forEach((t) => appliedGrid.createEl("span", { text: `#${t}`, cls: "dv-tag-chip dv-tag-chip-applied" }));
    this.responseEl.createEl("p", { text: `Added to frontmatter of "${note.title}"`, cls: "dv-autotag-hint" });
  }
  // ─── Daily Research Digest (v3.0.4) ──────────────────────────────────────
  async runDailyDigest(days) {
    const digestResponseEl = this._digestResponseEl;
    const digestExportRow = this._digestExportRow;
    if (!this.plugin.settings.apiKey) {
      digestResponseEl.empty();
      digestResponseEl.createEl("p", { text: "\u26A0\uFE0F Add your API key in Settings \u2192 Deep Vault", cls: "dv-error" });
      return;
    }
    digestResponseEl.empty();
    digestResponseEl.createEl("p", { text: `\u23F3 Scanning notes from the last ${days} day${days > 1 ? "s" : ""}...`, cls: "dv-thinking" });
    digestExportRow.addClass("dv-hidden");
    this.setStatus("\u23F3 Generating digest...");
    const cutoff = Date.now() - days * 24 * 60 * 60 * 1e3;
    const recentFiles = this.app.vault.getMarkdownFiles().filter((f) => f.stat.mtime > cutoff).sort((a, b) => b.stat.mtime - a.stat.mtime);
    if (recentFiles.length === 0) {
      digestResponseEl.empty();
      digestResponseEl.createEl("p", {
        text: `\u{1F4ED} No notes modified in the last ${days} day${days > 1 ? "s" : ""}.`,
        cls: "dv-placeholder"
      });
      this.setStatus("");
      return;
    }
    const filesToDigest = recentFiles.slice(0, 15);
    digestResponseEl.empty();
    digestResponseEl.createEl("p", {
      text: `\u23F3 Reading ${filesToDigest.length} recently modified notes...`,
      cls: "dv-thinking"
    });
    const noteChunks = [];
    for (const file of filesToDigest) {
      try {
        const content = await this.app.vault.read(file);
        const modDate = new Date(file.stat.mtime).toLocaleDateString();
        noteChunks.push(`## ${file.basename} (modified ${modDate})

${content.slice(0, 600).trim()}`);
      } catch (e) {
      }
    }
    digestResponseEl.empty();
    digestResponseEl.createEl("p", { text: "\u23F3 Asking Claude to generate digest...", cls: "dv-thinking" });
    const rangeLabel = days === 1 ? "the last 24 hours" : `the last ${days} days`;
    const prompt = `You are generating a daily research digest for an Obsidian user.

They have modified ${noteChunks.length} notes in ${rangeLabel}. Analyse these notes and create a structured digest with these sections:

## \u{1F4CA} Overview
Brief summary of what they worked on (2-3 sentences).

## \u{1F4A1} Key Ideas
The most important concepts or insights across all notes (bullet points).

## \u{1F517} Connections
Any interesting links or themes across different notes.

## \u2753 Open Questions
Unresolved questions or areas that need more research.

## \u2705 Suggested Next Steps
2-3 concrete things to do next based on this work.

Here are the notes:

${noteChunks.join("\n\n---\n\n")}`;
    try {
      const result = await callClaude(this.plugin.settings, [{ role: "user", content: prompt }], false);
      digestResponseEl.empty();
      renderMarkdown(digestResponseEl, result);
      this._lastDigestResult = result;
      this._lastDigestDays = days;
      this._lastDigestCount = filesToDigest.length;
      digestExportRow.removeClass("dv-hidden");
      this.chatHistory.push({
        role: "user",
        content: `[Daily Digest] Last ${days} day${days > 1 ? "s" : ""} \u2014 ${filesToDigest.length} notes`,
        timestamp: new Date()
      });
      this.chatHistory.push({ role: "assistant", content: result, timestamp: new Date() });
    } catch (err) {
      digestResponseEl.empty();
      digestResponseEl.createEl("p", { text: `\u274C ${err.message}`, cls: "dv-error" });
    }
    this.setStatus("");
  }
  async exportDigestAsNote() {
    const result = this._lastDigestResult;
    const days = this._lastDigestDays;
    const count = this._lastDigestCount;
    if (!result) {
      new import_obsidian4.Notice("No digest to export.");
      return;
    }
    const dateStr = formatDate(new Date());
    const label = days === 1 ? "Daily" : days === 7 ? "Weekly" : "Monthly";
    const content = `---
created: ${new Date().toISOString()}
source: Deep Vault
type: Research Digest
period: Last ${days} day${days > 1 ? "s" : ""}
notes_reviewed: ${count}
---

# ${label} Research Digest \u2014 ${dateStr}

${result}
`;
    await this.exportToNote(content, `${label} Digest`);
  }
  async callClaudeChat(messages, useWeb) {
    if (!this.plugin.settings.apiKey) {
      this.addChatBubble("assistant", "\u26A0\uFE0F Please add your Anthropic API key in **Settings \u2192 Deep Vault**.");
      return;
    }
    const thinkingWrap = this.addChatBubble("assistant", "...");
    if (useWeb) {
      const statusMsg = thinkingWrap.querySelector(".dv-thinking");
      if (statusMsg)
        statusMsg.textContent = "\u{1F310} Searching the web...";
    }
    try {
      const result = await callClaude(this.plugin.settings, messages, useWeb);
      thinkingWrap.remove();
      this.addChatBubble("assistant", result);
      this.chatHistory.push({ role: "assistant", content: result, timestamp: new Date() });
    } catch (err) {
      thinkingWrap.remove();
      this.addChatBubble("assistant", `\u274C Error: ${err.message}`);
    }
  }
  async onClose() {
  }
};
var DeepVaultPlugin = class extends import_obsidian4.Plugin {
  async onload() {
    await this.loadSettings();
    this.registerView(DEEP_VAULT_VIEW, (leaf) => new DeepVaultView(leaf, this));
    this.addRibbonIcon("search", "Deep Vault", () => this.activateView());
    this.addCommand({ id: "open-deep-vault", name: "Open Deep Vault panel", callback: () => this.activateView() });
    const tabCommands = [
      { id: "deep-vault-tab-research", name: "Deep Vault: Go to Research tab", tab: "research" },
      { id: "deep-vault-tab-chat", name: "Deep Vault: Go to Chat tab", tab: "chat" },
      { id: "deep-vault-tab-synthesis", name: "Deep Vault: Go to Synthesis tab", tab: "synthesis" },
      { id: "deep-vault-tab-templates", name: "Deep Vault: Go to Templates tab", tab: "templates" },
      { id: "deep-vault-tab-search", name: "Deep Vault: Go to Search tab", tab: "search" },
      { id: "deep-vault-tab-history", name: "Deep Vault: Go to History tab", tab: "history" }
    ];
    for (const cmd of tabCommands) {
      this.addCommand({
        id: cmd.id,
        name: cmd.name,
        callback: async () => {
          var _a;
          await this.activateView();
          const view = (_a = this.app.workspace.getLeavesOfType(DEEP_VAULT_VIEW)[0]) == null ? void 0 : _a.view;
          if (view)
            view.switchTabPublic(cmd.tab);
        }
      });
    }
    const actionCommands = [
      { id: "deep-vault-summarize", name: "Deep Vault: Summarise current note", action: "summarize" },
      { id: "deep-vault-questions", name: "Deep Vault: Generate research questions", action: "questions" },
      { id: "deep-vault-concepts", name: "Deep Vault: Extract key concepts", action: "concepts" },
      { id: "deep-vault-gaps", name: "Deep Vault: Find research gaps", action: "gaps" },
      { id: "deep-vault-connections", name: "Deep Vault: Find connections", action: "connections" },
      { id: "deep-vault-autotag", name: "Deep Vault: Auto-tag current note", action: "autotag" }
    ];
    for (const cmd of actionCommands) {
      this.addCommand({
        id: cmd.id,
        name: cmd.name,
        editorCallback: async () => {
          var _a;
          await this.activateView();
          const view = (_a = this.app.workspace.getLeavesOfType(DEEP_VAULT_VIEW)[0]) == null ? void 0 : _a.view;
          if (view) {
            view.switchTabPublic("research");
            view.runQuickAction(cmd.action);
          }
        }
      });
    }
    this.addCommand({
      id: "deep-vault-daily-digest",
      name: "Deep Vault: Generate daily research digest",
      callback: async () => {
        var _a;
        await this.activateView();
        const view = (_a = this.app.workspace.getLeavesOfType(DEEP_VAULT_VIEW)[0]) == null ? void 0 : _a.view;
        if (view) {
          view.switchTabPublic("research");
          view.runDailyDigest(1);
        }
      }
    });
    this.addCommand({
      id: "deep-vault-search",
      name: "Deep Vault: Search vault",
      callback: async () => {
        var _a;
        await this.activateView();
        const view = (_a = this.app.workspace.getLeavesOfType(DEEP_VAULT_VIEW)[0]) == null ? void 0 : _a.view;
        if (view)
          view.switchTabPublic("search");
      }
    });
    this.addCommand({
      id: "deep-vault-setup-wizard",
      name: "Deep Vault: Open setup wizard",
      callback: () => new SetupWizardModal(this.app, this).open()
    });
    this.addSettingTab(new DeepVaultSettingTab(this.app, this));
    this.app.workspace.onLayoutReady(() => {
      if (!this.settings.hasSeenWizard) {
        setTimeout(() => new SetupWizardModal(this.app, this).open(), 800);
      }
    });
    console.log("Deep Vault v3.1.2 loaded \u2705");
  }
  async activateView() {
    const { workspace } = this.app;
    let leaf = workspace.getLeavesOfType(DEEP_VAULT_VIEW)[0];
    if (!leaf) {
      leaf = workspace.getRightLeaf(false);
      await leaf.setViewState({ type: DEEP_VAULT_VIEW, active: true });
    }
    workspace.revealLeaf(leaf);
  }
  onunload() {
    this.app.workspace.detachLeavesOfType(DEEP_VAULT_VIEW);
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};
